# -*- coding: utf-8 -*-
"""IBMproject.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1evor7yaFl-RP8Mmth0WEoN9jqbiu-Zgy

# Import Drive
"""

from google.colab import drive
drive.mount('/content/drive')

"""# Import Libraries"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

"""## Importing The Datase"""

data1=pd.read_csv('/content/mental-and-substance-use-as-share-of-disease.csv')
data2=pd.read_csv('/content/prevalence-by-mental-and-substance-use-disorder.csv')

#Merging the Dataset for optimal results

dataset=pd.merge(data2,data1)
dataset.head()

"""## **Cleaning** the Dataset"""

dataset.isnull().sum()

dataset.drop('Code',axis=1,inplace=True)

dataset.isnull().sum()

dataset.set_axis(['Country','Year','Schizophrenia', 'Bipolar_disorder', 'Eating_disorder','Anxiety','drug_usage','depression','alcohol','mental_fitness'], axis='columns', inplace=True)

"""## *Encoding* the Categorical values"""

dataset.head()

from sklearn.preprocessing import LabelEncoder
l=LabelEncoder()
for i in dataset.columns:
    if dataset[i].dtype == 'object':
        dataset[i]=l.fit_transform(dataset[i])


dataset.head()

dataset['Country'].unique()

"""## Assigning feautre of Matrix and Dependent *Variable*"""

x=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

"""## Spliting the Dataset into Training data set and Testing data set"""

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

"""Implementing the Regression Algorithms and choose which one is better based on results

## 1)Linear **regression**
"""

from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)

#predicting the value

y_pred=lr.predict(x_test)

#evaluating the model

from sklearn.metrics import r2_score,mean_squared_error
print("Results for Linear Regression:\n1)Mean Square Error={}\n2)R-Square Score={}".format(mean_squared_error(y_test,y_pred),r2_score(y_test,y_pred)))

"""

2)SVM Regression"""

from sklearn.svm import SVR
svr=SVR()
svr.fit(x_train,y_train)

#predicting the value

y_pred=svr.predict(x_test)

#evaluating the model

from sklearn.metrics import r2_score,mean_squared_error
print("Results for SVM Regression:\n1)Mean Square Error={}\n2)R-Square Score={}".format(mean_squared_error(y_test,y_pred),r2_score(y_test,y_pred)))

"""### 3)Decision Tree Regression"""

from sklearn.tree import DecisionTreeRegressor
dtr=DecisionTreeRegressor(random_state=0)
dtr.fit(x_train,y_train)

#predicting the value

y_pred=dtr.predict(x_test)

#evaluating the model

from sklearn.metrics import r2_score,mean_squared_error
print("Results for Decision Tree Regression:\n1)Mean Square Error={}\n2)R-Square Score={}".format(mean_squared_error(y_test,y_pred),r2_score(y_test,y_pred)))

"""### 4)Random Forest Regression"""

from sklearn.ensemble import RandomForestRegressor
rfr= RandomForestRegressor(n_estimators=10,random_state=42)
rfr.fit(x_train,y_train)

#predicting the value

y_pred=rfr.predict(x_test)

#evaluating the model

from sklearn.metrics import r2_score,mean_squared_error
print("Results for Decision Tree Regression:\n1)Mean Square Error={}\n2)R-Square Score={}".format(mean_squared_error(y_test,y_pred),r2_score(y_test,y_pred)))

"""Conclusion:

# **Random Forest Regression works** well on both train and test sets with r2 score of 0.99.

## As well as **Decision Tree Regression** also works well on both train and test set with r2 score of 0.98.
"""

np.random.seed(range(0,100))
print("Welcome to Mental Fitness Tracker!\nFill the detail to check your mental fitness!")
country=l.fit_transform([input('Enter Your country Name:')])
year=int(input("Enter the Year:"))
schi=(float(input("Enter your Schizophrenia rate in % (it not enter 0):")))*100
bipo_dis=(float(input("Enter your Bipolar disorder rate in % (it not enter 0):")))*100
eat_dis=(float(input("Enter your Eating disorder rate in % (it not enter 0):")))*100
anx=(float(input("Enter your Anxiety rate in % (it not enter 0):")))*10
drug_use=(float(input("Enter your Drug Usage rate in per year % (it not enter 0):")))*100
depr=(float(input("Enter your Depression rate in % (it not enter 0):")))*10
alch=(float(input("Enter your Alcohol Consuming rate per year in % (it not enter 0):")))*100

prediction=rfr.predict([[country,year,schi,bipo_dis,eat_dis,anx,drug_use,depr,alch]])
print("Your Mental Fitness is {}%".format(prediction*10))
print("Thank you for checking ur mental fitness all ways smile :)")

"""Final Result of My Project is shown Above Good Working And Give Exact Result"""

